### ISSUE TITLE
How to setup in Docker on Windows 10 ?

### ISSUE THREAD

**Issue by RIS2000** [pulsejet/go-vod#23]
Hello!

Is it possible to setup in Docker on Windows 10 for streaming from Nextcloud in VMWare Ubuntu ?

How to do this ? Any instructions ?

Thanks!

**Comment by pulsejet** [comment]
I doubt it. You need to have the exact same file structure in your nextcloud instance and the docker container running go-vod. As such, the setup is mostly intended when you're running Nextcloud in docker too. Also I doubt it'll be any use because you probably can't pass the hardware acceleration devices through windows to docker (not sure though). But in that case the same should be possible in VMWare too, so you can just install the required drivers in your Nextcloud VM and be done with it.

**Comment by ChildLearningClub** [comment]
I think this is possible, within your ubuntu server you will need to setup a samba server. Then when you run the go-vod in Windows as a docker you will need to create a volume that has that share as the "device".

Example:

```
version: '3'

services:
  go-vod:
    image: go-vod
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    ports:
      - 47788:47788
    volumes:
      - data:/media/10TB-DRIVES/:ro


volumes:
  data:
    driver: local
    driver_opts:
      type: cifs
      o: "username=[username],password=[password]"
      device: "//192.168.37.50/10tb-drives"
```
for the [username] and [password] replace with the username and password that you use to login to your Ubuntu server.

device: "//192.168.37.50/10tb-drives" will be the IP address of your Ubuntu instance.
